# Le fichier YAML est à compléter

name: CI Node.js

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
name: Checkout code
uses: actions/checkout@v4

Installer les dépendances
name : Installer les dépendances
run  : npm install

Lancer les tests
name: Lancer les tests
run : npm test


Vérifier la syntaxe avec ESLint
name : Vérification ESLint
run  : npm run lint

Générer un build dans dist/
name : Générer le build
run  : mkdir dist/ && echo "Build" > build.txt

Afficher un message de succès
name : Message de succès
run  : echo "Build et tests réussis !"