# Le fichier YAML est à compléter

on: push

jobs:
  testActionGithub:
    runs-on: ubuntu-latest
    steps:
      - name: Active Npm install
        run: npm install
      - name: Active Npm run test
        run: npm run test
      - name: Vérification de la syntaxe avec ESLint
        run: eslint --ext .js
      - name: Générer un artefact de build
        run:
          mkdir -p dist
          echo "Build" > build.txt
      - name: Message de fin
        run: echo "Message de fin d'action"
